CREATE DATABASE LOJA_SUPLEMENTOS;
USE LOJA_SUPLEMENTOS;

CREATE TABLE PRODUTOS (
	ID 					INT 			AUTO_INCREMENT,
    NOME 				VARCHAR(255) 	NOT NULL,
    DESCRICAO 			TEXT,
    PRECO				DECIMAL(10,2) 	NOT NULL,
    QUANTIDADE_ESTOQUE  INT 			NOT NULL,
	
    CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)
);

CREATE TABLE CLIENTES (
    ID 			INT 			AUTO_INCREMENT,
    CPF 		VARCHAR(20) 	NOT NULL,
    NOME 		VARCHAR(255) 	NOT NULL,
    EMAIL 		VARCHAR(255) 	NOT NULL,
    TELEFONE 	VARCHAR(11) 	NOT NULL,
    ENDERECO 	TEXT 			NOT NULL,

    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
);

CREATE TABLE PEDIDOS (
    ID 				INT 			AUTO_INCREMENT,
    DTA_PEDIDO 		DATETIME 		NOT NULL,
    CLIENTE_ID		INT 			NOT	NULL,
    VALOR			DECIMAL(10,2)	NOT NULL,
    
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTE_2_PEDIDOS FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);

CREATE TABLE ITENS_PEDIDO (
    ID 			INT 	AUTO_INCREMENT,
    PEDIDO_ID 	INT 	NOT NULL,
    PRODUTO_ID 	INT 	NOT NULL,
    QUANTIDADE 	INT 	NOT NULL,
    
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_2_ITENS_PEDIDO 	FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
    CONSTRAINT FK_PRODUTO_2_ITENS_PEDIDO 	FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(ID)
);
