INSERT INTO LOJA_SUPLEMENTOS.PRODUTOS VALUES ( 1 , "WheyProtein","Pote de proteina 1kg", 100.00, 5);
INSERT INTO LOJA_SUPLEMENTOS.PRODUTOS VALUES ( 2, "BCAA","Pote de BCAA 300g", 50.00, 8);
INSERT INTO LOJA_SUPLEMENTOS.PRODUTOS VALUES ( 3, "Creatina","Pote de BCAA 300g", 150.00, 6);
INSERT INTO LOJA_SUPLEMENTOS.PRODUTOS VALUES ( 4, "Multivitaminico","Pote de Multivitaminico 100g", 50.00, 10);
INSERT INTO LOJA_SUPLEMENTOS.PRODUTOS VALUES ( 5, "Cafeina","Pote de Cafeina 100g", 30.00, 6);